### ISSUE TITLE
Hunter pet buffs triggering thanks

### ISSUE THREAD

**Issue by Ricoware** [Gogo1951/Thanks-for-the-Buff#2]
When a hunter pet casts a buff it will trigger a general thank you.  For example, wolf casting Furious Howl.

I made this change to the code to mitigate:

-- Ensure the source isn't the player (self-buff check)
if sourceGUID == UnitGUID("player") or sourceGUID == UnitGUID("pet") then
    return
end

**Comment by Gogo1951** [comment]
With what version? I thought I fixed this weeks ago. You on the latest?

**Comment by Ricoware** [comment]
I'm on Classic, latest version.  Look at line 96 of tftb.lua, it checks for "player" but not for "pet".

**Comment by Gogo1951** [comment]
https://github.com/Gogo1951/TFTB/commit/f5e0e494d74539fb601401822b356459d30c3a58

**Comment by Gogo1951** [comment]
Hey @Ricoware ,

I think it's fixed.

It's just so fucking shitty to test anything in this game.

Run around spamming Warlocks and Hunters, "Hey can you help me for a minute?" And it took literally 45 minutes of running around Stormwind to find a Warlock who would agree to the outrageous task of being invited to a group. 

Nobody responded, those that did were like, "10g?" or some variation of that.

I really love WoW, and I really hate like 99% of WoW players. (=

**Comment by Ricoware** [comment]
LOL  I know what you mean.  I've been mostly playing solo classic Hardcore so I didn't even think about pets of party members.  I've got the latest version and will be testing soon.

**Comment by Gogo1951** [comment]
I'm a little worried about Totem buffs.
